a,b=map(int,input().split())
if(a==1 or a==10):
    if(b%7==1):
        print('MON')
    elif(b%7==2):
        print('TUE')
    elif(b%7==3):
        print("WED")
    elif(b%7==4):
        print('THU')
    elif(b%7==5):
        print("FRI")
    elif(b%7==6):
        print('SAT')
    elif(b%7==0):
        print("SUN")
elif(a==2 or a==3 or a==11):
    if(b%7==1):
        print("THU")
    elif(b%7==2):
        print('FRI')
    elif(b%7==3):
        print("SAT")
    elif(b%7==4):
        print('SUN')
    elif(b%7==5):
        print("MON")
    elif(b%7==6):
        print('TUE')
    elif(b%7==0):
        print("WED")
elif(a==4 or a==7):
    if(b%7==1):
        print("SUN")
    elif(b%7==2):
        print('MON')
    elif(b%7==3):
        print("TUE")
    elif(b%7==4):
        print('WED')
    elif(b%7==5):
        print("THU")
    elif(b%7==6):
        print('FRI')
    elif(b%7==0):
        print("SAT")
elif(a==5):
    if(b%7==1):
        print("TUE")
    elif(b%7==2):
        print('WED')
    elif(b%7==3):
        print("THU")
    elif(b%7==4):
        print('FRI')
    elif(b%7==5):
        print("SAT")
    elif(b%7==6):
        print('SUN')
    elif(b%7==0):
        print("MON")
elif(a==6):
    if(b%7==1):
        print("FRI")
    elif(b%7==2):
        print('SAT')
    elif(b%7==3):
        print("SUN")
    elif(b%7==4):
        print('MON')
    elif(b%7==5):
        print("TUE")
    elif(b%7==6):
        print('WED')
    elif(b%7==0):
        print("THU")
elif(a==8):
    if(b%7==1):
        print("WED")
    elif(b%7==2):
        print('THU')
    elif(b%7==3):
        print("FRI")
    elif(b%7==4):
        print('SAT')
    elif(b%7==5):
        print("SUN")
    elif(b%7==6):
        print('MON')
    elif(b%7==0):
        print("TUE")
elif(a==12 or a==9):
    if(b%7==1):
        print("SAT")
    elif(b%7==2):
        print('SUN')
    elif(b%7==3):
        print("MON")
    elif(b%7==4):
        print('TUE')
    elif(b%7==5):
        print("WED")
    elif(b%7==6):
        print('THU')
    elif(b%7==0):
        print("FRI")
